/// Flutter icons OurIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  OurIcons
///      fonts:
///       - asset: fonts/OurIcons.ttf
///
///
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Fontelico, Copyright (C) 2012 by Fontello project
///         Author:    Crowdsourced, for Fontello project
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://fontello.com
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
///
import 'package:flutter/widgets.dart';

class OurIcons {
  OurIcons._();

  static const _kFontFam = 'OurIcons';
  static const String? _kFontPkg = null;

  static const IconData arrow_drop_down =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData attach_money =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brightness_4 =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brightness_7 =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData announcement =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instagram_1 =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emo_surprised =
      IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData snapchat_1 =
      IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData apple_1 =
      IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData adb =
      IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_a_photo =
      IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData android =
      IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instagram_square =
      IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dailymotion =
      IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pied_piper_square =
      IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spin6 =
      IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData firefox =
      IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chrome =
      IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData opera =
      IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ie =
      IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pinterest =
      IconData(0xf0d2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instagram =
      IconData(0xf16d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right =
      IconData(0xf178, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData apple =
      IconData(0xf179, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData snapchat =
      IconData(0xf2ab, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instagram_2 =
      IconData(0xf32d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData node_js =
      IconData(0xf3d3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sass =
      IconData(0xf41e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData amazon_pay =
      IconData(0xf42c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData php =
      IconData(0xf457, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData adobe =
      IconData(0xf778, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData artstation =
      IconData(0xf77a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData airbnb =
      IconData(0xf834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData biking =
      IconData(0xf84a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mdb =
      IconData(0xf8ca, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
