// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh_B6UFJwoA7WGiegpKBGL9MQaHVWNcB0',
    appId: '1:457393404516:android:28c790eea3271340be7d71',
    messagingSenderId: '457393404516',
    projectId: 'december-bw',
    storageBucket: 'december-bw.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnkGrQ1LMgI7p40I46MFkgDLIzchyX9vA',
    appId: '1:457393404516:ios:02e3ae05ffc25f23be7d71',
    messagingSenderId: '457393404516',
    projectId: 'december-bw',
    storageBucket: 'december-bw.appspot.com',
    androidClientId: '457393404516-mfmsank8i0dldbmbtpkau78cnv0tp0of.apps.googleusercontent.com',
    iosClientId: '457393404516-k9toku8628cov23dm1j7hfnq68l17sur.apps.googleusercontent.com',
    iosBundleId: 'com.example.httpApp',
  );
}
